// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://api.poipu-shores.com";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2cXFuZnNnb3ZseG9jamp1Z3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4NTQ2MzgsImV4cCI6MjA3OTQzMDYzOH0.iUzJqQoHRUJ0nmPU1t44OL9I-ZYtCDofNxAN14phjBQ";

// Storage preference key
const REMEMBER_ME_KEY = 'remember_me_preference';

// Check if user opted out of "Remember me"
const getStoragePreference = (): boolean => {
  try {
    return localStorage.getItem(REMEMBER_ME_KEY) !== 'false';
  } catch {
    return true; // Default to remember me
  }
};

// Set storage preference
export const setRememberMePreference = (remember: boolean): void => {
  try {
    if (remember) {
      localStorage.setItem(REMEMBER_ME_KEY, 'true');
    } else {
      localStorage.setItem(REMEMBER_ME_KEY, 'false');
    }
  } catch {
    // Storage not available
  }
};

// Get the appropriate storage based on preference
const getStorage = (): Storage => {
  return getStoragePreference() ? localStorage : sessionStorage;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the client with dynamic storage based on preference
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Switch storage for the current session (call before sign in)
export const switchToSessionStorage = (): void => {
  // Clear any existing localStorage auth data if switching to session storage
  const keysToRemove: string[] = [];
  for (let i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    if (key?.includes('supabase') || key?.includes('sb-')) {
      keysToRemove.push(key);
    }
  }
  keysToRemove.forEach(key => localStorage.removeItem(key));
};

// Switch storage for the current session (call before sign in)
export const switchToLocalStorage = (): void => {
  // Clear any existing sessionStorage auth data if switching to local storage
  const keysToRemove: string[] = [];
  for (let i = 0; i < sessionStorage.length; i++) {
    const key = sessionStorage.key(i);
    if (key?.includes('supabase') || key?.includes('sb-')) {
      keysToRemove.push(key);
    }
  }
  keysToRemove.forEach(key => sessionStorage.removeItem(key));
};